### ISSUE TITLE
N_MELL 

### ISSUE THREAD

**Issue by 980202006** [Qqi-HE/DeepChorus#2]
Thanks for your contribution, this paper is very useful in industry. In addition, should this 96 be 128?
![image](https://user-images.githubusercontent.com/24452502/159671532-56183571-a944-44bd-b96b-247114c43a6d.png)

**Comment by 980202006** [comment]
Should this equation be: t(m) = 0.5 × (mmax − mmin) + mmin
![image](https://user-images.githubusercontent.com/24452502/159671986-b7067b6a-b8a8-4e14-940b-68703b316ba9.png)

**Comment by Qqi-HE** [comment]
1. The wrong hyparameter was caused by mis-uploading of extract_features.py, I've uploaded the corrected file.
2. What the paper show is the correct equation.

**Comment by 980202006** [comment]
Thank you!
