### ISSUE TITLE
您好大佬，刚接触副歌提取的小白，问个问题

### ISSUE THREAD

**Issue by ghost** [Qqi-HE/DeepChorus#3]
大佬，模型的输出是二进制向量，表示副歌或非副歌，没明白什么意思！ 另外，模型能检测出位置副歌出现的具体时间位置嘛?

**Comment by Qqi-HE** [comment]
- 这句话的意思是：这个模型的输出是一个一位向量，每个element是0或1，0表示这一秒是副歌段落，反之则是副歌段落。
- 量化为1秒。

**Comment by ghost** [comment]
明白了，谢谢大佬
